# 设置端口号
server:
  port: 8081
# 配置服务应用名称
dubbo.application.name: provider-server
dubbo:
  # 设置注册中心地址
  registry:
    address: zookeeper://127.0.0.1:2181
  # 设置哪些服务要被扫描注册
  scan:
    base-packages: com.sky.boot.service.impl
